services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  nodeapp:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql       # <-- Important: service name, not IP
      DB_USER: user
      DB_PASS: password
      DB_NAME: testdb
      DB_PORT: 3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
